ci: add success job

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -213,3 +213,19 @@ jobs:
 #                        --define sonar.coverageReportPaths=${{runner.workspace}}/coverage.xml
 #                        --define sonar.cfamily.valgrind.reportsPaths=${{runner.workspace}}/valgrind.xml
 #                        --define sonar.analysis.cache.enabled=false
+
+    success:
+        runs-on: ubuntu-latest
+        needs:
+            - Test-Coverage
+            - Linter
+            - Valgrind
+        if: always()
+        steps:
+            -   name: Check dependences result
+                if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+                run: |
+                    echo "One or more required jobs failed."
+                    exit 1
+            -   name: Success
+                run: echo "CI passed."
